### ISSUE TITLE
[RFC] - Repository and Community Rename, Rebranding and Philosophy

### ISSUE THREAD

**Issue by tolstenko** [InfiniBrains/Awesome-GameDev-Resources#13]
# RFC - Repository and Community Rename, Rebranding, and Philosophy

**Feature Name:** Repository and Community Rename, Rebranding, and Philosophy

**Type:** Marketing, Product, and Community

**Start Date:** 2023-04-17

**End Date:** Decided by 2023-05-01

**Author:** 
- @tolstenko, @alecsantos96

## Summary

Improve the structure of our resources and community by creating better logos, names, branding, philosophies, and guidelines.

## Motivation

Currently, we have 57 members on Whatsapp group;
Successfully ran 1 meeting every single week for 2 months;
People are getting lost in the processes and goals;
Aim to steadily increase the community; 

## Detailed design

Every comment in this section should either be a proposal to be voted on via reactions or comments on any topic. Steps to propose a change: Select **only one topic**: Philosophy, Repo Name, Community name, or Logo, and post as a comment here. Wait for others to vote.

## Drawbacks

Lose some links or redirects that we already have.

## Alternatives

I really enjoy the strategy behind the web3devs community and thecherno. We could inspire ourselves by looking at them.

## Unresolved questions

Please help us nail down and define our future.

**Comment by tolstenko** [comment]
# Community Philosophy

This comment is a placeholder. I will edit it to match the proposal. I will do something similar to this one: https://docs.web3dev.com.br/termos/codigo-de-conduta

**Comment by tolstenko** [comment]
## Mascot

Credits to Alec; I will edit this later to reference it correctly.
![340042145_252624230537406_3414059740638181741_n](https://user-images.githubusercontent.com/2386417/232533307-4321ca99-bdbc-41c0-88d7-c3c3492d5349.jpg)

**Comment by Germano123** [comment]
For future references, in the date 10-05-2023 we decided that:

1. Repository
We'll be using [Infinibrains repository](https://github.com/InfiniBrains/Awesome-GameDev-Resources) until the community grow enough to have its own.

2. Community Rename
We'll be using the name Awesome GameDev Guild.

3. Rebranding
This topic is open until we recieve design proposal for identity.

4. Philosophy
This [document](https://docs.google.com/document/d/1XKNDtSqcrpmQi_aKUN3v6eRrZzNb_AybEiqtnE5mhbk/edit?usp=sharing) will have our guidelines and first steps.

**Comment by tolstenko** [comment]
Rules and philosophy here.
https://docs.google.com/document/d/1XKNDtSqcrpmQi_aKUN3v6eRrZzNb_AybEiqtnE5mhbk/edit?usp=sharing
