### ISSUE TITLE
[RFC] - Community model for events

### ISSUE THREAD

**Issue by Germano123** [InfiniBrains/Awesome-GameDev-Resources#17]
# English

# RFC Template

**Feature Name:** Community model for events

**Type:** Enhancement

**Start Date:** 22/04/2023

**End Date:** 27/05/2023

**Author:** Germano Gomes

**Related components:** Group events and organization

**issues:**
The current group event methodology may cause confusion with proposed long-term community models.

## Summary

To make the current model of events clearer, I am proposing an alignment of the types of events that we can adopt within the scope of the community's activities. Are they:
- Codingo dojo
- Art dojo
- Workshop
- Integrated design
- Lecture
- Bootcamps
- Contests

## Motivation

The intention of clarifying community activities is to prevent future events from being misinterpreted and to ensure that they are properly analyzed by the community to define internal advantages and benefits of the community (tokenization and interactions in events)

## Detailed design

Here follow a series of descriptions of each of the proposed events:
* Codingo dojo
It must be at least 2 hours long the dojo must intend to finalize a small project through the hands of everyone present at the event (it is not mandatory to go through everyone due to the event deadline) but having in mind the interaction of all. This model can be further divided into 2 or more meetings where it is expected that in the first moment there will be an explanation of the content that will be addressed together with the introduction of the challenge to be completed.

* Art dojo
This dojo adaptation allows practical/theoretical knowledge about a subject or tool to be passed on, but keeping the introduction aligned to only one meeting, so the introduction is concise and direct for the theme approach.

* Workshop
The common model of presentation and practice tracking that will be the standard for introducing new technologies. Practical approaches of a tool that can have a longer duration and follow-up than a meeting.

* Integrated design
In this model, it will be possible to participate in a project carried out by the community in order to practice and exchange development experiences in different lines with all members. Weekly/biweekly/monthly meetings are expected to align activities and decide on the final intention of the project.

* Lecture
The lecture must have a maximum duration of 2 hours. The speaker should bring as a theme something related to game development and if it is not possible to have an event aligned with this theme, we can bring options related to development technologies in general.

* Bootcamps
The idea is to bring together a group of people who want to try a technology and deepen their study with a constant commitment to meetings

* Contests
The contests will be a simple environment of proposed challenges so that those engaged have room to train on a specific topic and still have a reward as a benefit

## Drawbacks

This proposal may complicate future meeting intentions, bringing up the difficult decision of how to carry out the proposed exercise in the most practical way for those interested in holding an event

## Alternatives

Another alternative is to keep the current state and only have the description of 'Coding Dojo', 'Art Dojo' and courses. This means that in the future we will have complications in defining the participation of community members in terms of interaction in events.

## Unresolved questions

For this proposal, only future integrations of unsubmitted event proposals are open.

Edit: Added bootcamps and contests to event picklist.

# Português
# Modelo RFC

**Nome do recurso:** modelo de comunidade para eventos

**Tipo:** Aprimoramento

**Data de início:** 22/04/2023

**Data final:** 27/05/2023

**Autor:** Germano Gomes

**Componentes relacionados:** Eventos e organização do grupo

**problemas:**
A atual metodologia de eventos de grupo pode causar confusão com modelos comunitários de longo prazo propostos.

## Resumo

Para tornar mais claro o atual modelo de eventos, proponho um alinhamento dos tipos de eventos que podemos adotar no âmbito das atividades da comunidade. São eles:
- Dojô de código
- Dojô de arte
- Oficinas
- Projeto integrado
- Palestra
- Bootcamps
- Concursos

## Motivação

A intenção de esclarecer as atividades da comunidade é evitar que eventos futuros sejam mal interpretados e garantir que sejam devidamente analisados pela comunidade para definir vantagens e benefícios internos da comunidade (tokenização e interações em eventos)

## Projeto detalhado

Segue uma série de descrições de cada um dos eventos propostos:
* Codingo dojô
Deve ter no mínimo 2 horas de duração o dojo deve pretender finalizar um pequeno projeto pelas mãos de todos os presentes no evento (não é obrigatório passar por todos devido ao prazo do evento) mas tendo em vista a interação de todos. Este modelo pode ainda ser dividido em 2 ou mais encontros onde se espera que num primeiro momento haja uma explanação do conteúdo que será abordado juntamente com a introdução do desafio a cumprir.

* Arte dojô
Essa adaptação dojo permite que o conhecimento prático/teórico sobre um assunto ou ferramenta seja repassado, mas mantendo a introdução alinhada a apenas um encontro, de forma que a introdução seja concisa e direta para a abordagem do tema.

* Oficina
O modelo comum de apresentação e acompanhamento da prática que será o padrão para a introdução de novas tecnologias. Abordagens práticas de uma ferramenta que pode ter maior duração e acompanhamento do que uma reunião.

* Projeto integrado
Nesse modelo, será possível participar de um projeto realizado pela comunidade para praticar e trocar experiências de desenvolvimento em diversas linhas com todos os membros. Esperam-se reuniões semanais/quinzenais/mensais para alinhar as atividades e decidir sobre a intenção final do projeto.

* Palestra
A palestra deverá ter a duração máxima de 2 horas. O palestrante deverá trazer como tema algo relacionado ao desenvolvimento de jogos e caso não seja possível ter um evento alinhado com este tema, podemos trazer opções relacionadas a tecnologias de desenvolvimento em geral.

* Bootcamps
A ideia é reunir um grupo de pessoas que querem experimentar uma tecnologia e aprofundar seus estudos com uma aposta constante em encontros

* Concursos
Os concursos serão um ambiente simples de desafios propostos para que os engajados tenham espaço para treinar em um tema específico e ainda tenham como benefício uma recompensa

## Desvantagens

Essa proposta pode complicar as intenções de reuniões futuras, trazendo à tona a difícil decisão de como realizar o exercício proposto da forma mais prática para os interessados em realizar um evento

## Alternativas

Outra alternativa é manter o estado atual e ter apenas a descrição de 'Coding Dojo', 'Art Dojo' e cursos. Isso significa que no futuro teremos complicações em definir a participação dos membros da comunidade em termos de interação em eventos.

## Questões não resolvidas

Para esta proposta, apenas integrações futuras de propostas de eventos não enviadas estão abertas.

Edição: adição de bootcamps e concursos na lista de opções dos eventos.

**Comment by tolstenko** [comment]
Motion to approve?

**Comment by Germano123** [comment]
In a meeting it was decided that the proposed models will be used by the community.
