### ISSUE TITLE
[Coding Dojo] - Introdução a linguagem Rust

### ISSUE THREAD

**Issue by Dione-b** [InfiniBrains/Awesome-GameDev-Resources#24]
Tema:  Introdução a linguagem Rust
Pitch: Entendendo como funciona uma linguagem que prioriza segurança e performance

- Tools Required: [`no prerequisite, rust playground will be used`]
- Knowledge Required: [`basic data structures and algorithms`]

# Timeline Structure
### Covered Content:

- Rust Introduction
- Data types
- Variables
- Functions
- Conditionals
- Loops
- Match
- Enum
- Struct
- Tuples
- Memories
- Ownership
- Impl
- Strings

**Comment by tolstenko** [comment]
aula gravada aqui https://youtu.be/dSXHN8pi54k
